# %% [code] {"_execution_state":"idle","execution":{"iopub.status.busy":"2023-04-20T10:35:19.897977Z","iopub.execute_input":"2023-04-20T10:35:19.934543Z","iopub.status.idle":"2023-04-20T10:35:20.792186Z"},"jupyter":{"outputs_hidden":false}}
# This R environment comes with many helpful analytics packages installed
# It is defined by the kaggle/rstats Docker image: https://github.com/kaggle/docker-rstats
# For example, here's a helpful package to load

library(tidyverse) # metapackage of all tidyverse packages

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

list.files(path = "../input")

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# %% [code] {"execution":{"iopub.status.busy":"2023-04-20T11:27:41.249025Z","iopub.execute_input":"2023-04-20T11:27:41.250623Z","iopub.status.idle":"2023-04-20T11:27:41.263665Z"}}
library(tidyverse)


```